# Generated by Django 3.2.5 on 2021-08-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cards',
            field=models.ManyToManyField(blank=True, to='main.Card'),
        ),
    ]
