# Generated by Django 3.2.5 on 2021-08-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_carditem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carditem',
            old_name='item_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='carditem',
            old_name='item_value',
            new_name='value',
        ),
    ]
