# Generated by Django 3.2.5 on 2021-08-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(default='game', max_length=200),
        ),
    ]
