# Generated by Django 3.2.5 on 2021-08-11 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210810_0325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_name',
            new_name='tutorial_content',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_username',
        ),
        migrations.AddField(
            model_name='profile',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tutorial_title',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
