# Generated by Django 3.2.5 on 2021-08-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210824_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
