# Generated by Django 3.2.5 on 2021-08-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210824_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='text_content',
            field=models.CharField(blank=True, default='', max_length=99999),
        ),
        migrations.AlterField(
            model_name='card',
            name='items',
            field=models.ManyToManyField(blank=True, to='main.CardItem'),
        ),
    ]
