# Generated by Django 3.2.5 on 2021-08-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210824_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='text_content',
            new_name='content',
        ),
    ]
